#! /bin/bash -e

APP_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

echo "Running docker"
docker-compose -f $APP_ROOT/docker-compose.10-3.yml run --rm -d --service-ports postgres-10-3
